const translations = {
    zh: {
      welcome: "欢迎体验箭头屎（ArrowShit）！",
      home: "首页",
      whitepaper: "白皮书",
      community: "社区",
      intro: "箭头屎是一个基于 Solana 区块链的 meme 币，灵感来源于一坨形状酷似箭头的屎。它用幽默和讽刺直指加密市场的垃圾现象，提醒投资者回归理性。",
      join: "加入我们，用这坨屎一起嘲讽市场的荒谬！",
      join_now: "立即加入",
      view_whitepaper: "查看白皮书",
      join_community: "加入我们的社区！",
      overview: "1. 项目概述",
      overview_content: "箭头屎（ArrowShit）是一个基于 Solana 区块链的 meme 币，灵感来源于一次偶然的排泄物艺术——一坨形状酷似箭头的屎。这坨屎不仅是一个自然界的奇迹，更是我们对当前加密货币市场荒谬现象的深刻讽刺。在如今的 meme 币市场里，什么垃圾都能发币，什么币都有人买，甚至连屎也能变成“价值”。箭头屎代币应运而生，旨在用这坨屎指向那些发币诈骗、操控市场、盲目投机的行为，同时也让持有者可以用它“指向”自己讨厌的人，表达不满。",
      background: "2. 代币背景与叙事",
      origin: "2.1 起源",
      origin_content: "某天，项目创始人发现自己排泄出一坨形状完美的箭头屎，仿佛是大自然对加密市场的无声嘲讽。这坨屎不仅是一个艺术品，更是一个象征：<br>- 箭头：指向加密市场的垃圾现象——发币诈骗、操控市场、盲目投机。<br>- 屎：代表市场里那些毫无价值的“垃圾币”，却依然有人趋之若鹜。",
      market_deformities: "2.2 市场畸形现象",
      market_deformities_content: "在链上混久了，许多人的金钱观已经畸形：链上挥金如粪土，链下扣扣嗖嗖。链上动辄豪掷千金买一堆垃圾币，链下却连一杯奶茶都舍不得买。这种扭曲的金钱观正是箭头屎想要讽刺的核心——当人们在链上把钱当屎花，却忘了屎本身就是屎！箭头屎代币用这坨屎直指这种荒谬，提醒大家回归理性。",
      mission: "2.3 使命",
      mission_content: "箭头屎代币的使命是通过幽默和讽刺，让人们意识到 meme 币市场的荒谬，同时警醒投资者：不是所有币都有价值，有些只是“屎”！我们希望通过这坨屎，让社区成员反思加密市场的现状，同时用它来“指向”那些令人讨厌的行为或人。",
      tokenomics: "3. 代币经济学",
      token_name: "3.1 代币名称与符号",
      token_name_content: "名称：箭头屎（ArrowShit）<br>符号：ARROWSHIT",
      total_supply: "3.2 总供应量",
      total_supply_content: "总供应量：10 亿 ARROWSHIT（因为市场上有太多“屎”，我们决定让供应量足够大，讽刺那些随意发行的垃圾币。）发行方式：全部代币将通过市场自行认购，公开透明，任何人都有机会拥有一坨“屎”。",
      use_cases: "3.3 代币用途",
      use_cases_content: "- 讽刺工具：持有者可以用 ARROWSHIT“指向”市场上的垃圾项目或讨厌的人，表达态度。<br>- 社区活动：参与“最垃圾项目评选”等活动，赢取更多 ARROWSHIT。<br>- NFT 联动：未来将推出“屎 NFT”系列，持有者可以用 ARROWSHIT 购买独特的屎形 NFT。",
      vision: "4. 项目愿景",
      vision_content: "箭头屎代币并不追求成为“下一个比特币”，我们只想用这坨屎提醒大家：<br>- 不要盲目投资垃圾币，擦亮眼睛。<br>- 警惕发币诈骗和市场操控。<br>- 反思链上挥金如粪土、链下扣扣嗖嗖的畸形金钱观，重新审视“价值”的意义。<br>- 用幽默的方式表达对市场乱象的不满。",
      community_and_culture: "5. 社区与文化",
      community_content: "箭头屎的社区文化围绕“讽刺与警醒”展开。我们鼓励社区成员：<br>- 分享市场里的“垃圾币”案例，用 ARROWSHIT“指向”它们。<br>- 创作与箭头屎相关的 meme，推动项目的传播。<br>- 用 ARROWSHIT“指向”生活中或市场中讨厌的人或事，释放情绪。",
      technical: "6. 技术细节",
      technical_content: "- 区块链：Solana（因为它快，能让这坨屎迅速传播）。<br>- 合约：去中心化，代码开源（我们不搞那些“操控市场”的垃圾操作）。<br>- 交易费用：低手续费，象征性地“清理”市场垃圾。",
      risk: "7. 风险提示",
      risk_content: "- 这坨屎没有任何实际价值，买它纯属娱乐。<br>- 加密市场有风险，投资需谨慎，别真把屎当宝。<br>- 我们不保证这坨屎会涨价，但我们保证它会让你笑。",
      conclusion: "8. 结语",
      conclusion_content: "箭头屎（ArrowShit）是一坨有态度的屎，它指向加密市场的垃圾现象，也指向那些让人厌恶的行为，更指向链上挥金如粪土、链下扣扣嗖嗖的畸形金钱观。加入我们，用这坨屎一起嘲讽市场的荒谬，警醒投资者，同时释放你的情绪！让我们一起，用箭头屎指向垃圾市场！",
    },
    en: {
      welcome: "Welcome to ArrowShit!",
      home: "Home",
      whitepaper: "Whitepaper",
      community: "Community",
      intro: "ArrowShit is a meme coin on the Solana blockchain, inspired by a turd shaped like an arrow. It uses humor and satire to point at the trashy phenomena in the crypto market, reminding investors to stay rational.",
      join: "Join us and use this turd to mock the market’s absurdity!",
      join_now: "Join Now",
      view_whitepaper: "View Whitepaper",
      join_community: "Join Our Community!",
      overview: "1. Project Overview",
      overview_content: "ArrowShit is a meme coin on the Solana blockchain, inspired by an accidental piece of excrement art—a turd shaped like an arrow. This turd is not only a marvel of nature but also a profound satire of the absurdity in today’s cryptocurrency market. In today’s meme coin market, any trash can be tokenized, any coin can find buyers, and even shit can become “valuable.” The ArrowShit token was born to use this turd to point at scams, market manipulations, and blind speculations, while also allowing holders to “point” it at people they dislike to express their discontent.",
      background: "2. Token Background and Narrative",
      origin: "2.1 Origin",
      origin_content: "One day, the project founder discovered they had excreted a perfectly shaped arrow-like turd, as if it were nature’s silent mockery of the crypto market. This turd is not just a piece of art but also a symbol:<br>- Arrow: Pointing at the trashy phenomena in the crypto market—token scams, market manipulation, and blind speculation.<br>- Shit: Representing the worthless “trash coins” in the market that people still flock to.",
      market_deformities: "2.2 Market Deformities",
      market_deformities_content: "After spending too much time on-chain, many people’s sense of money has become distorted: on-chain, they spend money like it’s shit; off-chain, they’re stingy and penny-pinching. On-chain, they splurge thousands on trash coins, but off-chain, they’re reluctant to even buy a cup of bubble tea. This distorted sense of money is exactly what ArrowShit aims to satirize—when people on-chain treat money like shit, they forget that shit is just shit! The ArrowShit token uses this turd to directly point at this absurdity, reminding everyone to return to rationality.",
      mission: "2.3 Mission",
      mission_content: "The mission of ArrowShit is to use humor and satire to make people realize the absurdity of the meme coin market, while warning investors: not all coins have value—some are just “shit”! We hope that through this turd, community members will reflect on the current state of the crypto market and use it to “point” at annoying behaviors or people.",
      tokenomics: "3. Tokenomics",
      token_name: "3.1 Token Name and Symbol",
      token_name_content: "Name: ArrowShit<br>Symbol: ARROWSHIT",
      total_supply: "3.2 Total Supply",
      total_supply_content: "Total Supply: 1 billion ARROWSHIT (Because there’s so much “shit” in the market, we decided to make the supply large enough to mock those randomly issued trash coins.) Issuance Method: All tokens will be available for public subscription through the market, transparent and open, so anyone can own a piece of “shit.”",
      use_cases: "3.3 Token Use Cases",
      use_cases_content: "- Satire Tool: Holders can use ARROWSHIT to “point” at trashy projects or people they dislike, expressing their stance.<br>- Community Events: Participate in events like “Worst Project Awards” to win more ARROWSHIT.<br>- NFT Integration: In the future, we’ll launch a “Shit NFT” series, and holders can use ARROWSHIT to buy unique shit-shaped NFTs.",
      vision: "4. Project Vision",
      vision_content: "ArrowShit doesn’t aim to be the “next Bitcoin”; we just want to use this turd to remind everyone:<br>- Don’t blindly invest in trash coins—keep your eyes open.<br>- Be wary of token scams and market manipulation.<br>- Reflect on the distorted sense of money—spending like shit on-chain while being stingy off-chain—and reevaluate the meaning of “value.”<br>- Express dissatisfaction with market chaos in a humorous way.",
      community_and_culture: "5. Community and Culture",
      community_content: "The ArrowShit community culture revolves around “satire and awareness.” We encourage members to:<br>- Share examples of “trash coins” in the market and use ARROWSHIT to “point” at them.<br>- Create ArrowShit-related memes to spread the project.<br>- Use ARROWSHIT to “point” at annoying people or things in life or the market, releasing emotions.",
      technical: "6. Technical Details",
      technical_content: "- Blockchain: Solana (because it’s fast, allowing this turd to spread quickly).<br>- Contract: Decentralized, open-source code (we don’t engage in those “market manipulation” trash tactics).<br>- Transaction Fees: Low fees, symbolically “cleaning up” market trash.",
      risk: "7. Risk Warning",
      risk_content: "- This turd has no real value; buying it is purely for entertainment.<br>- The crypto market is risky, so invest cautiously—don’t actually treat shit like treasure.<br>- We don’t guarantee this turd will increase in value, but we guarantee it’ll make you laugh.",
      conclusion: "8. Conclusion",
      conclusion_content: "ArrowShit is a turd with attitude, pointing at the trashy phenomena in the crypto market, at annoying behaviors, and at the distorted sense of money—spending like shit on-chain while being stingy off-chain. Join us, and let’s use this turd to mock the market’s absurdity, warn investors, and release your emotions! Let’s together use ArrowShit to point at the trashy market!",
    },
    ja: {
      welcome: "ArrowShitへようこそ！",
      home: "ホーム",
      whitepaper: "ホワイトペーパー",
      community: "コミュニティ",
      intro: "ArrowShitはSolanaブロックチェーン上のミームコインで、矢印の形をしたうんこからインスピレーションを受けています。ユーモアと風刺を通じて、暗号市場のゴミのような現象を指し示し、投資家に理性を取り戻すよう促します。",
      join: "私たちに参加して、このうんこで市場の不条理を嘲笑しましょう！",
      join_now: "今すぐ参加",
      view_whitepaper: "ホワイトペーパーを見る",
      join_community: "コミュニティに参加しよう！",
      overview: "1. プロジェクト概要",
      overview_content: "ArrowShitはSolanaブロックチェーン上のミームコインで、偶然の排泄物アート—矢印の形をしたうんこからインスピレーションを受けています。このうんこは自然の奇跡であるだけでなく、今日の暗号通貨市場の不条理に対する深い風刺でもあります。現在のミームコイン市場では、どんなゴミでもトークン化でき、どんなコインでも買い手が見つかり、うんこさえも「価値」になり得ます。ArrowShitトークンはこのうんこを使って、トークンの詐欺、市場操作、盲目的な投機行為を指し示すために生まれました。また、ホルダーが嫌いな人を「指す」ことで不満を表現することもできます。",
      background: "2. トークンの背景とストーリー",
      origin: "2.1 起源",
      origin_content: "ある日、プロジェクトの創設者が完璧な矢印の形をしたうんこを排泄したところ、それはまるで暗号市場に対する自然の静かな嘲笑のようでした。このうんこは単なるアート作品ではなく、象徴でもあります：<br>- 矢印：暗号市場のゴミのような現象—トークンの詐欺、市場操作、盲目的な投機を指す。<br>- うんこ：市場にある価値のない「ゴミコイン」を表し、それでも人が群がる。",
      market_deformities: "2.2 市場の異常現象",
      market_deformities_content: "チェーン上で長く活動していると、多くの人の金銭感覚が歪んでしまいます：チェーン上では金をうんこのように使い、チェーン外ではケチで細かい。チェーン上ではゴミコインに何千も浪費しますが、チェーン外ではバブルティー一杯すら買うのを惜しみます。この歪んだ金銭感覚こそがArrowShitが風刺したい核心です—チェーン上で金をうんこのように扱うとき、うんこはうんこに過ぎないことを忘れているのです！ArrowShitトークンはこのうんこを使ってこの不条理を直接指し示し、皆に理性を取り戻すよう促します。",
      mission: "2.3 ミッション",
      mission_content: "ArrowShitのミッションは、ユーモアと風刺を通じてミームコイン市場の不条理を人々に認識させ、投資家に警告することです：すべてのコインに価値があるわけではなく、一部はただの「うんこ」に過ぎません！このうんこを通じて、コミュニティメンバーが暗号市場の現状を振り返り、迷惑な行動や人を「指す」ことを願っています。",
      tokenomics: "3. トークノミクス",
      token_name: "3.1 トークン名とシンボル",
      token_name_content: "名称：ArrowShit<br>シンボル：ARROWSHIT",
      total_supply: "3.2 総供給量",
      total_supply_content: "総供給量：10億ARROWSHIT（市場には「うんこ」が多すぎるため、供給量を十分に大きくして、ランダムに発行されるゴミコインを嘲笑することにしました。）発行方法：すべてのトークンは市場を通じて公開透明に購読可能で、誰でも「うんこ」を所有するチャンスがあります。",
      use_cases: "3.3 トークンの用途",
      use_cases_content: "- 風刺ツール：ホルダーはARROWSHITを使って市場のゴミプロジェクトや嫌いな人を「指して」態度を表現できます。<br>- コミュニティイベント：「最悪プロジェクト賞」などのイベントに参加して、さらにARROWSHITを獲得できます。<br>- NFT連携：将来的に「うんこNFT」シリーズを立ち上げ、ホルダーはARROWSHITを使ってユニークなうんこ型NFTを購入できます。",
      vision: "4. プロジェクトビジョン",
      vision_content: "ArrowShitは「次のビットコイン」を目指していません。このうんこを使って皆に思い出させたいだけです：<br>- ゴミコインに盲目的に投資しないで、目を擦ってください。<br>- トークンの詐欺や市場操作に注意してください。<br>- チェーン上で金をうんこのように使い、チェーン外でケチる歪んだ金銭感覚を振り返り、「価値」の意味を再評価してください。<br>- 市場の混乱に対する不満をユーモラスに表現してください。",
      community_and_culture: "5. コミュニティと文化",
      community_content: "ArrowShitのコミュニティ文化は「風刺と警鐘」を中心に展開されます。コミュニティメンバーに以下を奨励します：<br>- 市場の「ゴミコイン」の事例を共有し、ARROWSHITを使ってそれらを「指す」。<br>- ArrowShit関連のミームを作成してプロジェクトを広める。<br>- 生活や市場で嫌いな人や物にARROWSHITを「指して」感情を解放する。",
      technical: "6. 技術詳細",
      technical_content: "- ブロックチェーン：Solana（高速で、このうんこを迅速に広めることができるため）。<br>- コントラクト：分散化、オープンソースコード（市場操作のようなゴミ行為はしません）。<br>- 取引手数料：低手数料で、市場のゴミを象徴的に「掃除」します。",
      risk: "7. リスク警告",
      risk_content: "- このうんこには実際の価値はありません。購入は純粋にエンターテイメント目的です。<br>- 暗号市場にはリスクがあり、投資は慎重に行ってください。うんこを宝物として扱わないでください。<br>- このうんこが値上がりすることを保証しませんが、笑いを提供することは保証します。",
      conclusion: "8. 結論",
      conclusion_content: "ArrowShitは態度を持ったうんこです。暗号市場のゴミ現象、迷惑な行動、チェーン上で金をうんこのように使い、チェーン外でケチる歪んだ金銭感覚を指します。私たちに参加して、このうんこで市場の不条理を嘲笑し、投資家に警鐘を鳴らし、感情を解放しましょう！一緒にArrowShitを使ってゴミ市場を指しましょう！",
    },
    ko: {
      welcome: "ArrowShit에 오신 것을 환영합니다!",
      home: "홈",
      whitepaper: "백서",
      community: "커뮤니티",
      intro: "ArrowShit은 Solana 블록체인에서 시작된 밈 코인으로, 화살표 모양의 똥에서 영감을 받았습니다. 유머와 풍자를 통해 암호화폐 시장의 쓰레기 같은 현상을 지적하며, 투자자들에게 이성을 되찾으라고 촉구합니다.",
      join: "우리와 함께 이 똥으로 시장의 터무니없음을 조롱하세요!",
      join_now: "지금 가입하기",
      view_whitepaper: "백서 보기",
      join_community: "커뮤니티에 가입하세요!",
      overview: "1. 프로젝트 개요",
      overview_content: "ArrowShit은 Solana 블록체인에서 시작된 밈 코인으로, 우연히 발견된 배설물 예술—화살표 모양의 똥에서 영감을 받았습니다. 이 똥은 자연의 기적일 뿐만 아니라 오늘날 암호화폐 시장의 터무니없음에 대한 깊은 풍자이기도 합니다. 현재 밈 코인 시장에서는 어떤 쓰레기라도 토큰화될 수 있고, 어떤 코인이라도 구매자를 찾을 수 있으며, 심지어 똥도 “가치”가 될 수 있습니다. ArrowShit 토큰은 이 똥을 사용해 토큰 사기, 시장 조작, 맹목적인 투기 행위를 지적하기 위해 태어났습니다. 또한 홀더가 싫어하는 사람을 “지적”하여 불만을 표현할 수 있도록 합니다.",
      background: "2. 토큰 배경 및 스토리",
      origin: "2.1 기원",
      origin_content: "어느 날, 프로젝트 창시자가 완벽한 화살표 모양의 똥을 배설한 것을 발견했는데, 마치 자연이 암호화폐 시장을 조용히 조롱하는 것 같았습니다. 이 똥은 단순한 예술 작품이 아니라 상징이기도 합니다:<br>- 화살표: 암호화폐 시장의 쓰레기 같은 현상—토큰 사기, 시장 조작, 맹목적인 투기를 지적.<br>- 똥: 시장에 있는 가치 없는 “쓰레기 코인”을 나타내며, 그럼에도 불구하고 사람들이 몰려듭니다.",
      market_deformities: "2.2 시장의 기형적 현상",
      market_deformities_content: "온체인에서 오랫동안 활동하다 보면 많은 사람들의 금전 감각이 왜곡됩니다: 온체인에서는 돈을 똥처럼 쓰고, 오프체인에서는 인색하고 쩨쩨합니다. 온체인에서는 쓰레기 코인에 수천 달러를 아낌없이 쓰지만, 오프체인에서는 버블티 한 잔 사는 것도 아까워합니다. 이런 왜곡된 금전 감각이 바로 ArrowShit이 풍자하고자 하는 핵심입니다—온체인에서 돈을 똥처럼 취급할 때, 똥은 똥일 뿐이라는 사실을 잊어버립니다! ArrowShit 토큰은 이 똥으로 이런 터무니없음을 직접 지적하며, 모두에게 이성을 되찾으라고 촉구합니다.",
      mission: "2.3 미션",
      mission_content: "ArrowShit의 미션은 유머와 풍자를 통해 밈 코인 시장의 터무니없음을 사람들에게 깨닫게 하고, 투자자들에게 경고하는 것입니다: 모든 코인이 가치 있는 것은 아니며, 일부는 그저 “똥”일 뿐입니다! 이 똥을 통해 커뮤니티 멤버들이 암호화폐 시장의 현 상태를 돌아보고, 짜증나는 행동이나 사람을 “지적”하기를 바랍니다.",
      tokenomics: "3. 토큰 경제학",
      token_name: "3.1 토큰 이름 및 심볼",
      token_name_content: "이름: ArrowShit<br>심볼: ARROWSHIT",
      total_supply: "3.2 총 공급량",
      total_supply_content: "총 공급량: 10억 ARROWSHIT (시장에 “똥”이 너무 많기 때문에, 공급량을 충분히 크게 해서 무작위로 발행되는 쓰레기 코인을 조롱하기로 했습니다.) 발행 방식: 모든 토큰은 시장을 통해 공개적으로 투명하게 구독 가능하며, 누구나 “똥”을 소유할 기회를 가집니다.",
      use_cases: "3.3 토큰 사용 사례",
      use_cases_content: "- 풍자 도구: 홀더는 ARROWSHIT을 사용해 시장의 쓰레기 프로젝트나 싫어하는 사람을 “지적”하여 태도를 표현할 수 있습니다.<br>- 커뮤니티 이벤트: “최악 프로젝트 어워드”와 같은 이벤트에 참여하여 더 많은 ARROWSHIT을 획득할 수 있습니다.<br>- NFT 연계: 미래에 “똥 NFT” 시리즈를 출시할 예정이며, 홀더는 ARROWSHIT을 사용해 독특한 똥 모양 NFT를 구매할 수 있습니다.",
      vision: "4. 프로젝트 비전",
      vision_content: "ArrowShit은 “다음 비트코인”이 되려는 목표가 없습니다. 이 똥을 사용해 모두에게 상기시키고 싶을 뿐입니다:<br>- 쓰레기 코인에 맹목적으로 투자하지 말고, 눈을 뜨세요.<br>- 토큰 사기와 시장 조작에 주의하세요.<br>- 온체인에서 돈을 똥처럼 쓰고, 오프체인에서 인색한 왜곡된 금전 감각을 돌아보고, “가치”의 의미를 재평가하세요.<br>- 시장 혼란에 대한 불만을 유머러스하게 표현하세요.",
      community_and_culture: "5. 커뮤니티와 문화",
      community_content: "ArrowShit의 커뮤니티 문화는 “풍자와 경각심”을 중심으로 전개됩니다. 커뮤니티 멤버들에게 다음을 권장합니다:<br>- 시장의 “쓰레기 코인” 사례를 공유하고, ARROWSHIT을 사용해 그것들을 “지적”하세요.<br>- ArrowShit 관련 밈을 만들어 프로젝트를 확산시키세요.<br>- 삶이나 시장에서 싫어하는 사람이나 물건에 ARROWSHIT을 “지적”하여 감정을 해소하세요.",
      technical: "6. 기술 세부 사항",
      technical_content: "- 블록체인: Solana (빠르기 때문에 이 똥을 빠르게 확산시킬 수 있습니다).<br>- 계약: 분산화, 오픈소스 코드 (시장 조작과 같은 쓰레기 행위를 하지 않습니다).<br>- 거래 수수료: 낮은 수수료로, 상징적으로 시장 쓰레기를 “청소”합니다.",
      risk: "7. 리스크 경고",
      risk_content: "- 이 똥은 실제 가치가 없습니다. 구매는 순전히 엔터테인먼트 목적입니다.<br>- 암호화폐 시장에는 리스크가 있으니, 투자 시 주의하세요. 똥을 보물로 취급하지 마세요.<br>- 이 똥이 가치가 오를 것이라고 보장하지 않지만, 웃음을 줄 것이라고 보장합니다.",
      conclusion: "8. 결론",
      conclusion_content: "ArrowShit은 태도를 가진 똥입니다. 암호화폐 시장의 쓰레기 현상, 짜증나는 행동, 온체인에서 돈을 똥처럼 쓰고 오프체인에서 인색한 왜곡된 금전 감각을 지적합니다. 우리와 함께 이 똥으로 시장의 터무니없음을 조롱하고, 투자자들에게 경각심을 일깨우며, 감정을 해소합시다! 함께 ArrowShit을 사용해 쓰레기 시장을 지적합시다!",
    },
    fr: {
      welcome: "Bienvenue chez ArrowShit !",
      home: "Accueil",
      whitepaper: "Livre blanc",
      community: "Communauté",
      intro: "ArrowShit est un jeton mème sur la blockchain Solana, inspiré par un étron en forme de flèche. Il utilise l'humour et la satire pour pointer du doigt les phénomènes absurdes du marché des cryptomonnaies, rappelant aux investisseurs de rester rationnels.",
      join: "Rejoignez-nous et utilisez cet étron pour vous moquer de l'absurdité du marché !",
      join_now: "Rejoindre maintenant",
      view_whitepaper: "Voir le livre blanc",
      join_community: "Rejoignez notre communauté !",
      overview: "1. Aperçu du projet",
      overview_content: "ArrowShit est un jeton mème sur la blockchain Solana, inspiré par une œuvre d’art accidentelle d’excrément—un étron en forme de flèche. Cet étron n’est pas seulement une merveille de la nature, mais aussi une satire profonde de l’absurdité du marché des cryptomonnaies actuel. Dans le marché des jetons mème d’aujourd’hui, n’importe quel déchet peut être tokenisé, n’importe quel jeton peut trouver des acheteurs, et même la merde peut devenir “précieuse”. Le jeton ArrowShit est né pour utiliser cet étron afin de pointer du doigt les escroqueries de tokens, les manipulations de marché et les spéculations aveugles, tout en permettant aux détenteurs de le “pointer” vers des personnes qu’ils n’aiment pas pour exprimer leur mécontentement.",
      background: "2. Contexte et narration du jeton",
      origin: "2.1 Origine",
      origin_content: "Un jour, le fondateur du projet a découvert qu’il avait excrété un étron parfaitement formé en forme de flèche, comme si c’était une moquerie silencieuse de la nature envers le marché des cryptomonnaies. Cet étron n’est pas seulement une œuvre d’art, mais aussi un symbole :<br>- Flèche : Pointant les phénomènes absurdes du marché des cryptomonnaies—escroqueries de tokens, manipulation de marché et spéculation aveugle.<br>- Merde : Représentant les “jetons poubelle” sans valeur sur le marché, auxquels les gens se ruent néanmoins.",
      market_deformities: "2.2 Déformations du marché",
      market_deformities_content: "Après avoir passé trop de temps sur la blockchain, la perception de l’argent de nombreuses personnes s’est déformée : sur la chaîne, ils dépensent de l’argent comme si c’était de la merde ; hors chaîne, ils sont avares et pingres. Sur la chaîne, ils dépensent des milliers pour des jetons poubelle, mais hors chaîne, ils hésitent même à acheter une tasse de thé à bulles. Cette perception déformée de l’argent est exactement ce que ArrowShit vise à satiriser—quand les gens sur la chaîne traitent l’argent comme de la merde, ils oublient que la merde n’est que de la merde ! Le jeton ArrowShit utilise cet étron pour pointer directement cette absurdité, rappelant à tous de revenir à la rationalité.",
      mission: "2.3 Mission",
      mission_content: "La mission d’ArrowShit est d’utiliser l’humour et la satire pour faire prendre conscience aux gens de l’absurdité du marché des jetons mème, tout en avertissant les investisseurs : tous les jetons n’ont pas de valeur—certains ne sont que de la “merde” ! Nous espérons qu’à travers cet étron, les membres de la communauté réfléchiront à l’état actuel du marché des cryptomonnaies et l’utiliseront pour “pointer” des comportements ou des personnes agaçantes.",
      tokenomics: "3. Tokenomics",
      token_name: "3.1 Nom et symbole du jeton",
      token_name_content: "Nom : ArrowShit<br>Symbole : ARROWSHIT",
      total_supply: "3.2 Offre totale",
      total_supply_content: "Offre totale : 1 milliard d’ARROWSHIT (Parce qu’il y a tellement de “merde” sur le marché, nous avons décidé de rendre l’offre suffisamment grande pour moquer ces jetons poubelle émis au hasard.) Méthode d’émission : Tous les jetons seront disponibles pour une souscription publique via le marché, de manière transparente et ouverte, afin que chacun puisse posséder un morceau de “merde”.",
      use_cases: "3.3 Cas d’utilisation du jeton",
      use_cases_content: "- Outil de satire : Les détenteurs peuvent utiliser ARROWSHIT pour “pointer” des projets poubelle ou des personnes qu’ils n’aiment pas, exprimant ainsi leur position.<br>- Événements communautaires : Participez à des événements comme les “Prix du pire projet” pour gagner plus d’ARROWSHIT.<br>- Intégration NFT : À l’avenir, nous lancerons une série de “NFT Merde”, et les détenteurs pourront utiliser ARROWSHIT pour acheter des NFT uniques en forme de merde.",
      vision: "4. Vision du projet",
      vision_content: "ArrowShit n’aspire pas à devenir le “prochain Bitcoin” ; nous voulons juste utiliser cet étron pour rappeler à tous :<br>- Ne pas investir aveuglément dans des jetons poubelle—gardez les yeux ouverts.<br>- Méfiez-vous des escroqueries de tokens et des manipulations de marché.<br>- Réfléchissez à la perception déformée de l’argent—dépenser comme de la merde sur la chaîne tout en étant avare hors chaîne—et réévaluez la signification de la “valeur”.<br>- Exprimez votre mécontentement face au chaos du marché de manière humoristique.",
      community_and_culture: "5. Communauté et culture",
      community_content: "La culture de la communauté ArrowShit tourne autour de la “satire et de la sensibilisation”. Nous encourageons les membres à :<br>- Partager des exemples de “jetons poubelle” sur le marché et utiliser ARROWSHIT pour les “pointer”.<br>- Créer des mèmes liés à ArrowShit pour diffuser le projet.<br>- Utiliser ARROWSHIT pour “pointer” des personnes ou des choses agaçantes dans la vie ou sur le marché, libérant ainsi leurs émotions.",
      technical: "6. Détails techniques",
      technical_content: "- Blockchain : Solana (parce qu’elle est rapide, permettant à cet étron de se répandre rapidement).<br>- Contrat : Décentralisé, code open-source (nous ne nous engageons pas dans des tactiques poubelle comme la manipulation de marché).<br>- Frais de transaction : Frais faibles, nettoyant symboliquement les déchets du marché.",
      risk: "7. Avertissement sur les risques",
      risk_content: "- Cet étron n’a aucune valeur réelle ; l’acheter est purement pour le divertissement.<br>- Le marché des cryptomonnaies est risqué, alors investissez prudemment—ne traitez pas vraiment la merde comme un trésor.<br>- Nous ne garantissons pas que cet étron augmentera en valeur, mais nous garantissons qu’il vous fera rire.",
      conclusion: "8. Conclusion",
      conclusion_content: "ArrowShit est un étron avec une attitude, pointant les phénomènes absurdes du marché des cryptomonnaies, les comportements agaçants, et la perception déformée de l’argent—dépenser comme de la merde sur la chaîne tout en étant avare hors chaîne. Rejoignez-nous, et utilisons cet étron pour nous moquer de l’absurdité du marché, avertir les investisseurs et libérer vos émotions ! Ensemble, utilisons ArrowShit pour pointer le marché poubelle !",
    },
  };

  document.addEventListener('DOMContentLoaded', function() {
    const langSelect = document.getElementById('language');
    const currentLang = langSelect.value;
    const selectedOption = langSelect.querySelector(`option[value="${currentLang}"]`);
    langSelect.title = selectedOption.textContent;
    
    // 只显示当前语言的简短显示文本
    langSelect.style.width = 'auto';
    langSelect.style.minWidth = '44px';
  });
  
  function changeLanguage() {
    const lang = document.getElementById('language').value;
    document.querySelectorAll('[data-lang]').forEach(element => {
      const key = element.getAttribute('data-lang');
      element.innerHTML = translations[lang][key];
    });
  }
  
  window.onload = () => changeLanguage();